dist: xenial

env:
  global:
    - CC_TEST_REPORTER_ID=b5260482480f0b98b0a18b0e7f7225664abc22d3b23fa3555fdf0de694aee213

language: python
python:
  - 3.5
  - 3.6

env:
  - SNIPSKIT_REQUIREMENTS=common
  - SNIPSKIT_REQUIREMENTS=mqtt
  - SNIPSKIT_REQUIREMENTS=hermes
  - SNIPSKIT_REQUIREMENTS=all

install:
  - pip install -r requirements/install/$REQUIREMENTS.txt
  - pip install -r requirements/development.txt

before_script:
  - [ "$SNIPSKIT_REQUIREMENTS" == "all" ] && export PYTEST_ADDOPTS="--cov src --cov-report xml"
  - [ "$SNIPSKIT_REQUIREMENTS" == "all" ] && curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - [ "$SNIPSKIT_REQUIREMENTS" == "all" ] && chmod +x ./cc-test-reporter
  - [ "$SNIPSKIT_REQUIREMENTS" == "all" ] && ./cc-test-reporter before-build

script:
  - pytest --verbose
  - [ "$SNIPSKIT_REQUIREMENTS" == "all" ] && scripts/check_examples.sh
  - [ "$SNIPSKIT_REQUIREMENTS" == "all" ] && scripts/generate_docs.sh
  - [ "$SNIPSKIT_REQUIREMENTS" == "all" ] && scripts/build_package.sh

after_script:
  - [ "$SNIPSKIT_REQUIREMENTS" == "all" ] && ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
