dist: xenial

env:
  global:
    - CC_TEST_REPORTER_ID=b5260482480f0b98b0a18b0e7f7225664abc22d3b23fa3555fdf0de694aee213
    - INTEGRATION_TESTS=true
  matrix:
    - SNIPSKIT_REQUIREMENTS=all
    - SNIPSKIT_REQUIREMENTS=mqtt
    - SNIPSKIT_REQUIREMENTS=hermes
    - SNIPSKIT_REQUIREMENTS=common

language: python
python:
  - 3.5
  - 3.6
  - 3.7

before_install:
  - sudo apt-get install -y dirmngr apt-transport-https
  - sudo bash -c  'echo "deb https://debian.snips.ai/stretch stable main" > /etc/apt/sources.list.d/snips.list'
  - sudo apt-key add snips.gpg.key
  - sudo apt-get update -qq
  - sudo apt-get install -y snips-platform-common snips-dialogue snips-nlu snips-tts mosquitto

install:
  - pip install -r requirements/install/$SNIPSKIT_REQUIREMENTS.txt
  - pip install -r requirements/development.txt
  - pip install -r requirements/packaging.txt

before_script:
  - source scripts/travis/before_script.sh

script:
  - scripts/travis/script.sh

after_script:
  - scripts/travis/after_script.sh
