dist: xenial

env:
  global:
    - CC_TEST_REPORTER_ID=b5260482480f0b98b0a18b0e7f7225664abc22d3b23fa3555fdf0de694aee213

language: python
python:
  - 3.5
  - 3.6

install:
  - pip install -r requirements/install.txt
  - pip install -r requirements/tests.txt
  - pip install -r requirements/docs.txt

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - pytest --cov src --verbose --cov-report xml
  - cd docs && make html
  - cd ..

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
