dist: xenial

env:
  global:
    - CC_TEST_REPORTER_ID=b5260482480f0b98b0a18b0e7f7225664abc22d3b23fa3555fdf0de694aee213

language: python
python:
  - 3.5
  - 3.6

env:
  - SNIPSKIT_REQUIREMENTS=all
  - SNIPSKIT_REQUIREMENTS=mqtt
  - SNIPSKIT_REQUIREMENTS=hermes
  - SNIPSKIT_REQUIREMENTS=common

install:
  - pip install -r requirements/install/$SNIPSKIT_REQUIREMENTS.txt
  - pip install -r requirements/development.txt

before_script:
  - source scripts/travis/before_script.sh || travis_terminate 1

script:
  - scripts/travis/script.sh || travis_terminate 1

after_script:
  - scripts/travis/after_script.sh || travis_terminate 1
